GET http://localhost:8080/v1/histories
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmZDA3MmRmYTM4MDU2NzlmMTZmZTQxNzM4YzJhM2FkM2Y5MGIyMTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3BsaXRiaWxsLTg2NDQwIiwiYXVkIjoic3BsaXRiaWxsLTg2NDQwIiwiYXV0aF90aW1lIjoxNzMzMTMwNTM4LCJ1c2VyX2lkIjoiazVMREhFSFg2YWVNNjZrcmhxSFdvVDF4eGhnMiIsInN1YiI6Ims1TERIRUhYNmFlTTY2a3JocUhXb1QxeHhoZzIiLCJpYXQiOjE3MzMxMzA1MzgsImV4cCI6MTczMzEzNDEzOCwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAdGVzdC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.N3GvNGvXv_h8dMgCjYezkvVzMCNpgedVQmSiuWjkAfz-gILGWo7UgGT-itT9EfUDC9jRhsb1UGlZIbrWknbnFxbbjASSblynqEC7X2KzGAMqcQ14Mhot2x7iVZnbufZRAAhrJzElQ_TQJrY54-nkpYMxYh6ohr7B_CYx-fr1JnEkFaZGBZemXMmx2RD31qRFh-KTIR24GThcqY2v4Cyw0msmdYsx3_80DZDvFN6XT-nRHQE_2n__SAc0OFpgh-tJn-A0k9Lk_a3uDH3aw4XybjHzaRLjijkFePeyGdd89zSOyw2jDOtSGEKVtJGjwUEHSIBEoKQKdPQQroPmyZj_4g
###
GET http://localhost:8080/v1/histories/edd76e0b-01f6-43d5-8dbc-4b399f391ee9
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmZDA3MmRmYTM4MDU2NzlmMTZmZTQxNzM4YzJhM2FkM2Y5MGIyMTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3BsaXRiaWxsLTg2NDQwIiwiYXVkIjoic3BsaXRiaWxsLTg2NDQwIiwiYXV0aF90aW1lIjoxNzMzMTMzMDIzLCJ1c2VyX2lkIjoiazVMREhFSFg2YWVNNjZrcmhxSFdvVDF4eGhnMiIsInN1YiI6Ims1TERIRUhYNmFlTTY2a3JocUhXb1QxeHhoZzIiLCJpYXQiOjE3MzMxMzMwMjMsImV4cCI6MTczMzEzNjYyMywiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAdGVzdC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.pW5JC6R6aiufjTJC6R_AdCA5jAVWCev1cBwaxhWhoDb2BWKYlmYdFZz5LTtMF2yqWjBiOQmdw9Q0_4YAtnOIMdSisJReb21r94X-muIJ-OOcdQ9JP8LNjkd_HkMvSSQC-ZomAabFITOELI2jYjQRJgY0RozN4EKpLfGZLL5qtRXChMLL2NCYdknhEM5XdbKxUuWny_onYVbkystgcOgETR2dk86H1NOq1V1N3DfIrjMVycatu-L88qAVMOW0Xefz0iuCTXt4PJuwPsp7cgplcdK5Q5202qZGe5XptW-RUJIEvju4fqiQZGO-wIBB8mkdMG9DGIkGhvJpWfBJ8lzDkg
###
POST http://localhost:8080/v1/histories
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmZDA3MmRmYTM4MDU2NzlmMTZmZTQxNzM4YzJhM2FkM2Y5MGIyMTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3BsaXRiaWxsLTg2NDQwIiwiYXVkIjoic3BsaXRiaWxsLTg2NDQwIiwiYXV0aF90aW1lIjoxNzMzMTMwNTM4LCJ1c2VyX2lkIjoiazVMREhFSFg2YWVNNjZrcmhxSFdvVDF4eGhnMiIsInN1YiI6Ims1TERIRUhYNmFlTTY2a3JocUhXb1QxeHhoZzIiLCJpYXQiOjE3MzMxMzA1MzgsImV4cCI6MTczMzEzNDEzOCwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAdGVzdC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.N3GvNGvXv_h8dMgCjYezkvVzMCNpgedVQmSiuWjkAfz-gILGWo7UgGT-itT9EfUDC9jRhsb1UGlZIbrWknbnFxbbjASSblynqEC7X2KzGAMqcQ14Mhot2x7iVZnbufZRAAhrJzElQ_TQJrY54-nkpYMxYh6ohr7B_CYx-fr1JnEkFaZGBZemXMmx2RD31qRFh-KTIR24GThcqY2v4Cyw0msmdYsx3_80DZDvFN6XT-nRHQE_2n__SAc0OFpgh-tJn-A0k9Lk_a3uDH3aw4XybjHzaRLjijkFePeyGdd89zSOyw2jDOtSGEKVtJGjwUEHSIBEoKQKdPQQroPmyZj_4g
content-type: application/json

{
  "billName": "name",
  "items": [
    { "id": 1, "name": "abc", "payers": [1, 2], "price": 50 },
    { "id": 2, "name": "bcd", "payers": [2, 3], "price": 20 },
    { "id": 3, "name": "def", "payers": [1, 2, 3], "price": 30 }
  ],
  "payers": [
    { "id": 1, "name": "a", "amount": 0 },
    { "id": 2, "name": "b", "amount": 0 },
    { "id": 3, "name": "c", "amount": 0 }
  ]
}


###

PUT http://localhost:8080/v1/histories/09dfe04f-7121-4784-8fa5-0e7310299ae5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmZDA3MmRmYTM4MDU2NzlmMTZmZTQxNzM4YzJhM2FkM2Y5MGIyMTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3BsaXRiaWxsLTg2NDQwIiwiYXVkIjoic3BsaXRiaWxsLTg2NDQwIiwiYXV0aF90aW1lIjoxNzMzMDkyMTMwLCJ1c2VyX2lkIjoiazVMREhFSFg2YWVNNjZrcmhxSFdvVDF4eGhnMiIsInN1YiI6Ims1TERIRUhYNmFlTTY2a3JocUhXb1QxeHhoZzIiLCJpYXQiOjE3MzMwOTIxMzAsImV4cCI6MTczMzA5NTczMCwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAdGVzdC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Kpiuvk4-RoHXp-E2YrMxwfBPZrApjQznkzevUfMSTcKawdqnAcpLD3qI4_1DJmdm_n_Ikqp4jJiYWHUHlSZPZo3qfB3duwAIU8pjXtjrI4-gRDuaCelog4glQEyVd_2JjrMiUm8DrLyppfqN2LLFFFBCXqF5cnXcSqr-5gsuQC6CL_VSNhIlF2tFYfijlOZd5P8f7oGumx-jGRKIuW9H2bdyeq7tghzdm730cQu4-CVvGQ5sNWUc1W3Y5vrc0lZ2WNpvjQEUMJjH6Xeq-5peb1dehaGEZh3naMFZkrxkMyOsFwHp3o5vPiXbAQ6378UKDSfB51RTN7u6j9iMuFMHHw
content-type: application/json

{"billName":"edited bill","items":[{"id":1,"name":"abc","payers":[1,2],"price":50},{"id":2,"name":"bcd","payers":[2,3],"price":20}],"payers":[{"id":1,"name":"a","amount":25},{"id":2,"name":"b","amount":35},{"id":3,"name":"c","amount":10}]}
###
DELETE http://localhost:8080/v1/histories/2697a94e-154a-492d-a131-4e020d6a8a79
Authorization: Bearer eeyJhbGciOiJSUzI1NiIsImtpZCI6IjFlNTIxYmY1ZjdhNDAwOGMzYmQ3MjFmMzk2OTcwOWI1MzY0MzA5NjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3BsaXRiaWxsLTg2NDQwIiwiYXVkIjoic3BsaXRiaWxsLTg2NDQwIiwiYXV0aF90aW1lIjoxNzMxOTI0Mjc4LCJ1c2VyX2lkIjoiazVMREhFSFg2YWVNNjZrcmhxSFdvVDF4eGhnMiIsInN1YiI6Ims1TERIRUhYNmFlTTY2a3JocUhXb1QxeHhoZzIiLCJpYXQiOjE3MzE5MjQyNzgsImV4cCI6MTczMTkyNzg3OCwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAdGVzdC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Lw4SOpN18Q61fZVoZoCpdhrGDX5oWTCcrh5oxAtWK76tiyed7K7lUnEZKU38zhuefikZb9qtN3ssF-NH9z63Rkad_Y0Viw5zEx5uH8gzErsn7ycIhwiHIykbpkBWNeCB_7I217KYWnDiqe5nwtllsayZDj2-MaiTFmllmAcKAXxU6lJveUAy9qJIE1re_I8mTFlc02IwUOdVfKytackBEq6xRGPP403FoQgnEEUh80KB1b9dC_EYlIquyvNG3zc12pA4-idG51wjbg95b504K1rFaYAWDSJBlegYQfQn947FiHXIDL6FBFTFP4JOhhZQETKi4aM95txvbl28XyMNsQ