apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-bill-dev-deployment
  namespace: split-bill-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: summer-workshop-split-bill
          image: ghcr.io/secretlabrat/splitbill-backend:55015e3237621a8f4aeda3adb6aee97762a235cc
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: server.port
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: splitbill-firebase
                  key: firebase-project-id
            - name: FIREBASE_ADMIN_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: splitbill-firebase
                  key: firebase-admin-client-email
            - name: FIREBASE_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: splitbill-firebase
                  key: firebase-admin-key
          livenessProbe:
            httpGet:
              path: /v1/healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 20
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
              cpu: "0.25"
              memory: 128Mi
